---
- name: creating psql airflow user
  command: psql -c 'CREATE USER airflow;'
  become_user: postgres

- name: creating psql airflow db
  command: psql -c 'CREATE DATABASE airflow;'
  become_user: postgres

- name: making airflow superuser 
  command: psql -c 'ALTER USER airflow WITH SUPERUSER;'
  become_user: postgres
