---
- name: create airflow group
  group:
    name: airflow
    state: present

- name: Allow 'airflow' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%airflow'
    line: '%airflow ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: add airflow user to airflow sudo group
  user:
    name: airflow
    group: airflow
    shell: /bin/bash
    createhome: no
    state: present
    append: yes

- name: create airflow home
  file:
    path: "/home/airflow_home"
    owner: airflow
    group: airflow
    state: directory

- name: set airflow home dir as environment variable
  lineinfile:
    path: /etc/environment
    line: 'AIRFLOW_HOME=/home/airflow_home'

- name: apt installs as airflow
  include_role:
    name: base
  vars:
    user: airflow

- name: airflow pip installs including 'apache-airflow'
  become: airflow
  become_method: sudo
  pip:
    executable: pip3
    name: ['psycopg2-binary', 'apache-airflow']

