---

- name: initialize airflow db
  command: "airflow initdb"

- name: change airflow files permissions
  file:
    path: /home/de-devtools/airflow/unittests.cfg
    owner: airflow
    group: airflow
    mode: '660'

- name: set airflow metadata db to local postgres
  lineinfile:
    path: ~/airflow/airflow.cfg
    regexp: '^sql_alchemy_conn = sqlite:.*$'
    line: 'sql_alchemy_conn = postgres://postgres@localhost:5432'
    state: present

- name: set airflow metadata db to local postgres
  lineinfile:
    path: ~/airflow/airflow.cfg
    regexp: '^load_examples = True.*$'
    line: 'load_examples = False'
    state: present

- name: reset db again with postgres conn
  command: "service postgresql start && airflow resetdb --yes"
