---
# airflow database objects for meta data management
- name: postgres db config to trust airflow
  include: postgres-trust-airflow.yaml

- name: start postgres as service
  include: postgres-start-service.yaml

- name: create airflow db objects
  include: postgres-airflow-config.yaml

# airflow install config and deploy
- name: install apache airflow
  include: airflow-install.yaml

- name: config apache airflow
  include: airflow-config.yaml
